# Generated by Django 2.0.3 on 2018-10-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaToppings',
            new_name='PizzaTopping',
        ),
    ]
