# Generated by Django 2.0.8 on 2018-10-07 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181002_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzacrust',
            name='sort_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizzasize',
            name='sort_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizzastyle',
            name='sort_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
